### ISSUE TITLE
About evaluation result

### ISSUE THREAD

**Issue by mychina75** [xindongzhang/ECBSR#7]
Hi~ one more question..
As you know, the y channel super resolution result has to merge back to all channels' image, which are simple resized up.
so, when I compute the PSNR using the color image, result is not good as the evaluation result during training.
the x3 model test using DIV2K val DB. the PSNR result drop from 31.0x to 29.x...

anything wrong? thank you.

**Comment by xindongzhang** [comment]
> Hi~ one more question..
> As you know, the y channel super resolution result has to merge back to all channels' image, which are simple resized up.
> so, when I compute the PSNR using the color image, result is not good as the evaluation result during training.
> the x3 model test using DIV2K val DB. the PSNR result drop from 31.0x to 29.x...
> 
> anything wrong? thank you.

Hi there. For benchmark validation, please calculating the indexes(PSNR/SSIM) on Y channel out of YCbcr. And from the aspect of engineering, one could concat the dnn-upscaled-Y channels to the resized-Cb&Cr for visualizing or color-format-transfer. It shows little influence for visual effect, but there may be indexes drop because of the simply resized-Cb&Cr channels. I hope this could help.
